[package]
name = "assertion-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
revm = "12.1.0"
serde = { version = "1.0.208", features = ["derive"] }
sled = { version = "1.0.0-alpha.122" }
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.40"

[features]
test = []

[dev-dependencies]
rand = "0.8.5"
