[package]
name = "assertion-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
revm = "12.1.0"
serde = { version = "1.0.208", features = ["derive"] }
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.40"

# ETL deps
mending = { git = "ssh://git@github.com/phylaxsystems/mending.git", rev = "0c28f98c6"}
sled = { version = "1.0.0-alpha.122" }
anyhow = "1.0.89"
reth-db-api = { git = "https://github.com/paradigmxyz/reth.git", rev = "17aa3d61f"}
reth-db = { git = "https://github.com/paradigmxyz/reth.git", rev = "17aa3d61f"}
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth.git", rev = "17aa3d61f"}
bincode = "1.3.3"

[net]
git-fetch-with-cli = true

[features]
test = []

[dev-dependencies]
rand = "0.8.5"
