name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
                phylaxsystems/op-talos
                ghcr.io/phylaxsystems/op-talos
            tags: |
                type=sha

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            labels: ${{ steps.meta.outputs.labels }}
            tags: ${{ steps.meta.outputs.tags }}