name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
                ghcr.io/phylaxsystems/assertion-executor
            tags: |
                type=sha

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup ssh-agent
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Initialize Git submodules
          run: git submodule update --init --recursive

        - name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@nightly

        - uses: Swatinem/rust-cache@v2

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
            version: nightly

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build binary
          run: make build

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            labels: ${{ steps.meta.outputs.labels }}
            tags: ${{ steps.meta.outputs.tags }}