name: Release and Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          CARGO_VERSION=$(cargo read-manifest | jq -r .version)
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Version mismatch: Tag version ($TAG_VERSION) does not match Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi

  release-github:
    needs: check-version
    permissions:
      contents: write
    uses: phylaxsystems/actions/.github/workflows/release-github.yaml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
