name: Rust Test, Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust-base-linux:
    name: Rust Base (Linux)
    uses: phylaxsystems/actions/.github/workflows/rust-base.yaml@main
    with:
      rust-channel: "nightly"
      require-lockfile: true
      install-foundry: true
      dind: true
      submodules: "recursive"
      requires-private-deps: true
      foundry-command: "forge build --root contract-mocks"
      feature-sets: '["", "--features=optimism"]'
      runner: "ubuntu-latest" # Explicitly specify Linux runner
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}